POST http://localhost:5000/api/v1/add-quote
Content-Type: application/json

{
  "id": 123,
  "quote": "Bir başyapıt oluşturmak için önce temeli sağlam kurmak gerekir.",
  "writer": "Jane Doe",
  "categoryId": 4
}
###
