POST http://127.0.0.1:8083/user/forgot-password/mailer
Content-Type: application/json

{
  "email": "me.serhaterdem@gmail.com"

}
###
PATCH http://127.0.0.1:8083/user/forgot-password/auth
Accept: application/json
Content-Type: application/json

{
  "code": "715432",
  "email": "me.serhaterdem@gmail.com"

}
###
PATCH http://127.0.0.1:8083/user/forgot-password/reset-password
Accept: application/json
Content-Type: application/json

{
  "uuid": "3827cd98-cacd-4801-88fe-bb8faf1e28ff",
  "password": "XPly.3451.dsad"

}