POST http://127.0.0.1:8083/user/forgot-password/mailer
Content-Type: application/json

{
  "email": "me.serhaterdem@gmail.com"

}
###
PATCH http://127.0.0.1:8083/user/forgot-password/auth
Accept: application/json
Content-Type: application/json

{
  "code": "799239",
  "email": "me.serhaterdem@gmail.com"


}
###
PATCH http://127.0.0.1:8083/user/forgot-password/reset-password
Accept: application/json
Content-Type: application/json

{
  "uuid": "40d95b49-db91-4d82-b9a3-7a9def726bf7",
  "password": "XPly.3451.dsad"

}