POST http://127.0.0.1:8083/user/forgot-password/mailer
Content-Type: application/json

{
  "email": "yssk32000@gmail.com"

}
###
PATCH http://127.0.0.1:8083/user/forgot-password/auth
Accept: application/json
Content-Type: application/json

{
  "code": "432201",
  "email": "yssk32000@gmail.com"

}
###
PATCH http://127.0.0.1:8083/user/forgot-password/reset-password
Accept: application/json
Content-Type: application/json

{
  "uuid": "f2560de8-4419-4372-99e1-431f6700796e",
  "password": "XPly.3451.dsad"

}