POST http://127.0.0.1:8083/user/login
Accept: application/json
Content-Type: application/json

{
  "email": "me.serhaterdem@gmail.com",
  "password": "123A.sadasd3fsdA"

}

###
PATCH http://127.0.0.1:8083/user/resetpassword/confirm
Content-Type: application/json

{
  "code": "029793",
  "newPassword":"123A.sadasd3fsdA"

}

###


###
POST http://127.0.0.1:8083/user/reset-password/auth
Content-Type: application/json


{
  "email": "me.serhaterdem@gmail.com"
}

###
GET http://localhost:8083
Accept: application/json

###
POST http://localhost:8083/user/register
Content-Type: application/json

{
  "id": 123,
  "name": "Ali",
  "surname": "Erdem",
  "email": "editkuragma@gmail.com",
  "password": "fdsfdAffsf.3451.",
  "gender": "male",
  "profilePhotoPath": "/path/to/profile/photo.jpg"
}
###

DELETE http://localhost:8083/user/delete
Content-Type: application/json

{

  "email": "john.dose@hhffejjxample.com",
  "password": "Xfdsfds.3451."

}
###


PATCH http://localhost:8083/user/update
Content-Type: application/json

{
  "userLogin": {
    "email": "me.serhaterdem@gmail.com",
    "password": "ERdem.3451."
  },
  "updatedUserData": {
    "id": 123,
    "name": "John",
    "surname": "Doe",
    "email": "me.serhaterdem@gmail.com",
    "password": "ERdem.3451.",
    "gender": "male",
    "profilePhotoPath": "/path/to/photo.jpg"
  }
}

###








