name: Deploy Ktor to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Decode application.conf
        run: echo "${{ secrets.APPLICATIONCONF }}" | base64 --decode > src/main/resources/application.conf

      - name: Decode firebase_service_key.json
        run: echo "${{ secrets.FIREBASE_SERVICE_KEY }}" | base64 --decode > src/main/resources/firebase_service_key.json

      - name: Decode keystore.jks
        run: echo "${{ secrets.KEYSTORE_JKS }}" | base64 --decode > keystore.jks

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew clean shadowJar

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ktor-app
          path: build/libs/*.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: ktor-app
          path: .

      - name: Test SSH Connection
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
          chmod 600 private_key
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          ssh -i private_key ec2-user@${{ secrets.SSH_HOST }} 'echo "SSH connection works!"'

      - name: Deploy to EC2
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "SSH_USER is set to: $SSH_USER"
          echo "$SSH_KEY" > private_key && chmod 600 private_key
          mkdir -p ~/.ssh
          ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts
          scp -i private_key *.jar $SSH_USER@$SSH_HOST:/home/$SSH_USER/ktor-app.jar

      - name: Delete Artifact Locally
        run: |
          echo "Deleting local artifact..."
          rm -f *.jar

      - name: Restart Ktor Server
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "SSH_USER is set to: $SSH_USER"
          echo "$SSH_KEY" > private_key && chmod 600 private_key
          ssh -i private_key $SSH_USER@$SSH_HOST << EOF
          echo "Restarting Ktor server..."
          pkill -f 'java -jar' || true
          sudo nohup java -jar /home/$SSH_USER/ktor-app.jar > log.txt 2>&1 &
          EOF
