- name: Test SSH Connection
  run: |
    echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
    chmod 600 private_key
    ssh -i private_key ec2-user@${{ secrets.SSH_HOST }} 'echo "SSH connection works!"'
